{
 "title": "Cluster",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ]
  }
 ]
}
{
 "title": "Apps",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Frontend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Games",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "rate(app_games_total[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Wins Per Player",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(app_winner) (increase(app_wins_total[$__range]))",
     "legendFormat": "{{app_winner}}"
    }
   ]
  },
  {
   "title": "HTTP Client",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(http_status_code, net_peer_name) (rate(http_client_duration_count[5m]))",
     "legendFormat": "{{net_peer_name}} - code {{http_status_code}}"
    }
   ]
  },
  {
   "title": "HTTP Server Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "sum by(http_status_code) (rate(http_server_duration_count{job=\"frontend-deployment\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(job, le) (rate(http_server_duration_bucket{job=\"frontend-deployment\"}[5m])))",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(job, le) (rate(http_server_duration_bucket{job=\"frontend-deployment\"}[5m])))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(job, le) (rate(http_server_duration_bucket{job=\"frontend-deployment\"}[5m])))",
     "legendFormat": "99th percentile"
    }
   ]
  },
  { "title": "Backend1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "HTTP Server Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by(http_status_code) (rate(http_server_duration_count{job=\"backend1-deployment\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(job, le) (rate(http_server_duration_bucket{job=\"backend1-deployment\"}[5m])))",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(job, le) (rate(http_server_duration_bucket{job=\"backend1-deployment\"}[5m])))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(job, le) (rate(http_server_duration_bucket{job=\"backend1-deployment\"}[5m])))",
     "legendFormat": "99th percentile"
    }
   ]
  },
  {
   "title": "Backend1 (Prometheus metrics)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dice Rolls",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 75 },
     "targets": [
      {
       "expr": "sum(rate(dice_roll_count_total[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Dice Numbers Count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 75 },
     "targets": [
      {
       "expr": "sum by(number) (rate(dice_numbers_count_total[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Dice Numbers",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 75 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(number) (increase(dice_numbers_count_total[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Python Garbage Collection",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
     "targets": [
      {
       "expr": "sum by(generation) (rate(python_gc_collections_total[$__rate_interval]))",
       "legendFormat": "generation {{generation}}"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "timeseries",
     "description": "This assumes one core - to adjust, modify the \"Divide by scalar\" value to the number of cores you're running",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by(pod) (rate(process_cpu_seconds_total{container=\"backend1\"}[$__rate_interval])) * 100 / 1",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Backend2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "HTTP Server Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum by(http_status_code) (rate(http_server_duration_count{job=\"backend2-deployment\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(job, le) (rate(http_server_duration_bucket{job=\"backend2-deployment\"}[5m])))",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(job, le) (rate(http_server_duration_bucket{job=\"backend2-deployment\"}[5m])))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(job, le) (rate(http_server_duration_bucket{job=\"backend2-deployment\"}[5m])))",
     "legendFormat": "99th percentile"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_runtime_jvm_cpu_utilization",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "sum by(pool, type) (process_runtime_jvm_memory_usage)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}
{
 "title": "Collector",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Receivers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Receiver Success",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(receiver) (rate(otelcol_receiver_accepted_metric_points[$__rate_interval]))",
     "legendFormat": "{{receiver}} metrics"
    },
    {
     "expr": "sum by(receiver) (rate(otelcol_receiver_accepted_spans[$__rate_interval]))",
     "legendFormat": "{{receiver}} traces"
    }
   ]
  },
  {
   "title": "Receiver Refused",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(receiver) (rate(otelcol_receiver_refused_spans[$__rate_interval]))",
     "legendFormat": "{{receiver}} traces"
    },
    {
     "expr": "sum by(receiver) (rate(otelcol_receiver_refused_metric_points[$__rate_interval]))",
     "legendFormat": "{{receiver}} metrics"
    }
   ]
  },
  {
   "title": "Scrapes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(job) (scrape_samples_scraped)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(job) (scrape_duration_seconds)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Processors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Processor Accepted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by(processor) (rate(otelcol_processor_accepted_metric_points[$__rate_interval]))",
     "legendFormat": "{{processor}} metrics"
    },
    {
     "expr": "sum by(processor) (rate(otelcol_processor_accepted_spans[$__rate_interval]))",
     "legendFormat": "{{processor}} spans"
    }
   ]
  },
  {
   "title": "Processor Dropped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "targets": [
    {
     "expr": "sum by(processor) (rate(otelcol_processor_dropped_metric_points[$__rate_interval]))",
     "legendFormat": "{{processor}} metrics"
    },
    {
     "expr": "sum by(processor) (rate(otelcol_processor_dropped_spans[$__rate_interval]))",
     "legendFormat": "{{processor}} traces"
    }
   ]
  },
  {
   "title": "Processor Refused",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "expr": "sum by(processor) (rate(otelcol_processor_refused_metric_points[$__rate_interval]))",
     "legendFormat": "{{processor}} metrics"
    },
    {
     "expr": "sum by(processor) (rate(otelcol_processor_refused_spans[$__rate_interval]))",
     "legendFormat": "{{processor}} traces"
    }
   ]
  },
  { "title": "Exporters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Exporter Success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum by(exporter) (rate(otelcol_exporter_sent_metric_points[$__rate_interval]))",
     "legendFormat": "metrics {{exporter}}"
    },
    {
     "expr": "sum by(exporter) (rate(otelcol_exporter_sent_spans[$__rate_interval]))",
     "legendFormat": "traces {{exporter}}"
    }
   ]
  },
  {
   "title": "Exporter Enqueue Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "targets": [
    {
     "expr": "sum by(exporter) (rate(otelcol_exporter_enqueue_failed_log_records[$__rate_interval]))",
     "legendFormat": "{{exporter}} logs"
    },
    {
     "expr": "sum by(exporter) (rate(otelcol_exporter_enqueue_failed_metric_points[$__rate_interval]))",
     "legendFormat": "{{exporter}} metrics"
    },
    {
     "expr": "sum by(exporter) (rate(otelcol_exporter_enqueue_failed_spans[$__rate_interval]))",
     "legendFormat": "{{exporter}} traces"
    }
   ]
  },
  {
   "title": "exporter failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "expr": "sum by(exporter) (rate(otelcol_exporter_send_failed_metric_points[$__rate_interval]))",
     "legendFormat": "{{exporter}} metrics"
    },
    {
     "expr": "sum by(exporter) (rate(otelcol_exporter_send_failed_spans[$__rate_interval]))",
     "legendFormat": "{{exporter}} traces"
    }
   ]
  },
  { "title": "Spanmetrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Server Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum by(service_name, span_name) (rate(converted_calls{span_kind=\"SPAN_KIND_SERVER\"}[$__rate_interval]))",
     "legendFormat": "{{service_name}} - {{span_name}}"
    }
   ]
  },
  {
   "title": "Server Calls Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(converted_duration_bucket{span_kind=\"SPAN_KIND_SERVER\"}[$__rate_interval])))",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(converted_duration_bucket{span_kind=\"SPAN_KIND_SERVER\"}[$__rate_interval])))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(converted_duration_bucket{span_kind=\"SPAN_KIND_SERVER\"}[$__rate_interval])))",
     "legendFormat": "99th percentile"
    }
   ]
  },
  {
   "title": "Client Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum by(service_name, span_name) (rate(converted_calls{span_kind=\"SPAN_KIND_CLIENT\"}[$__rate_interval]))",
     "legendFormat": "{{service_name}} - {{span_name}}"
    }
   ]
  },
  {
   "title": "Internal Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "sum by(service_name, span_name) (rate(converted_calls{span_kind=\"SPAN_KIND_INTERNAL\"}[$__rate_interval]))",
     "legendFormat": "{{service_name}} - {{span_name}}"
    }
   ]
  }
 ]
}
{
 "title": "Target Allocator",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Service Discovery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SD Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(event) (rate(prometheus_sd_kubernetes_events_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SD HTTP Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(prometheus_sd_http_failures_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Allocation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Targets Per Collector",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "avg by(collector_name) (opentelemetry_allocator_targets_per_collector)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Num Collectors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "avg(opentelemetry_allocator_collectors_allocatable)",
     "legendFormat": "allocatable"
    },
    {
     "expr": "avg(opentelemetry_allocator_collectors_discovered)",
     "legendFormat": "discovered"
    }
   ]
  },
  {
   "title": "Allocation Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(opentelemetry_allocator_time_to_allocate_bucket[$__rate_interval])))",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(opentelemetry_allocator_time_to_allocate_bucket[$__rate_interval])))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(opentelemetry_allocator_time_to_allocate_bucket[$__rate_interval])))",
     "legendFormat": "99th percentile"
    }
   ]
  },
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by(path) (rate(opentelemetry_allocator_http_duration_seconds_sum[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(opentelemetry_allocator_http_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(opentelemetry_allocator_http_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(opentelemetry_allocator_http_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "99th percentile"
    }
   ]
  },
  {
   "title": "Metrics Handler Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "expr": "sum by(code, pod) (rate(promhttp_metric_handler_requests_total[$__rate_interval]))",
     "legendFormat": "{{pod}} - {{code}}"
    }
   ]
  },
  { "title": "Machine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "This assumes one core - to adjust, modify the \"Divide by scalar\" value to the number of cores you're running",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(process_cpu_seconds_total{service=\"otel-prom-cr-targetallocator\"}[$__rate_interval])) * 100 / 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "expr": "sum by(pod) (go_goroutines{service=\"otel-prom-cr-targetallocator\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}
{
 "title": "Loki Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "OpenTelemetry Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{exporter=\"OTLP\"} |= ``"
    }
   ]
  }
 ]
}